### ISSUE TITLE
swagger 2.0

### ISSUE THREAD

**Issue by z0mt3c** [z0mt3c/hapi-swaggered#3]

**Comment by grabbou** [comment]
Need any help on that? I've choosen your library after playing around with plenty of similar available and by far this is the only one that does not have a problem with nested schema arrays!

**Comment by z0mt3c** [comment]
Thank you for noticing ;-) An alpha version is already published to npm (alpha: '2.0.0-alpha.2'). Basically it's just the tests (including some top-level integration tests), their coverage and some beta-testing which is left until a stable release. Feel free to support!

https://travis-ci.org/z0mt3c/hapi-swaggered/builds

```js
63 tests complete
Test duration: 297 ms
No global variable leaks detected
Coverage: 98.65% (11/813)
lib/generator.js missing coverage on line(s): 18, 19, 21, 23
lib/index.js missing coverage on line(s): 72, 73
lib/resources.js missing coverage on line(s): 24, 29, 38
lib/utils.js missing coverage on line(s): 232, 246
Code coverage below threshold: 98.65 < 99
```

**Comment by grabbou** [comment]
Great, will check it out! I'm still impressed by the fact it handles all my nested objects with custom classNames without event a single collision!

**Comment by z0mt3c** [comment]
Switched branches... work is now happening in master.

**Comment by grabbou** [comment]
Do you need any help with that? As I said, lovely plugin, unfortunately not that popular as other swagger library which used to be full of bugs (at least when I used it for the last time)

**Comment by z0mt3c** [comment]
I think it's close to stable - got the coverage up, feels solid, may just #15 left (feel free to discuss) :-) Are you on the latest alpha?

**Comment by grabbou** [comment]
Just went back to lower version as mentioned in a different issue due to the grouping problems ;)

**Comment by z0mt3c** [comment]
Done

**Comment by grabbou** [comment]
Ok. I am updating to the lastest version to see what had changed.

**Comment by grabbou** [comment]
Unfortunately still throwin an error. Latest version + 1.3.0 UI.
```js
model.js:223 Uncaught TypeError: Cannot read property '$ref' of undefined
```
No call stack available, but the issue is here:

```js
if (_.isUndefined(item.$ref))
```

Item for some reason is undefined (which is weird) as there's a `map` method being called on an array, like `data.map(item => {})`.

**Comment by grabbou** [comment]
I think the issue is because in the generated swagger output, `items` element looks like this:
```js
"items":{"$ref":"#/definitions/IdTitleBuiltInModel"}}
```
So it looks like swagger expects an array to appear there?

**Comment by grabbou** [comment]
Further observations...

The error actually occurs here:

```js
Resolver.prototype.resolveTo = function (property, objs) {
  var ref = property.$ref;

  if (ref) {
    if (ref.indexOf('http') === 0) {
      if (Array.isArray(objs[ref])) {
        objs[ref].push({obj: property, resolveAs: '$ref'});
      } else {
        objs[ref] = [{obj: property, resolveAs: '$ref'}];
      }
    }
  } else if (property.type === 'array') {
    var items = property.items;
    // items is undefined here!
    this.resolveTo(items, objs);
  }
};
```

**Comment by z0mt3c** [comment]
Yeah true under this condition it creates an invalid schema. I hit this issue once as well - but for some reason i decided not to fix this.... may i didnt know which type to choose as fallback and decided to let swagger-ui handle it :-) But an uncaught typeerror is pretty unsatisfying.... should we go for string? what do you think?

**Comment by z0mt3c** [comment]
Follow up @ #22

**Comment by grabbou** [comment]
Cool, thanks. I've managed to fix the issue on my side, all good. I think I am gonna provide extended schema validation in the small framework I am currently working on anyway as `any` value is not a good `rest` approach.
